### ISSUE TITLE
Frontend terminates when connection to mysql database is lost

### ISSUE THREAD

**Issue by lhy-hoyin** [CS3219-AY2324S1/ay2324s1-course-assessment-g32#147]
Steps to replicate:
1. Start normally; Frontend (port 3000) and "backend"  (port 3001) works normally
2. "Kill" MySQL server
3. Frontend webpack is throw an error that causes it to terminate
4. Cannot see frontend (localhost:3000) anymore

Webpack error log:
``` shell
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Socket.<anonymous> (D:\Users\NUS\Desktop\PeerPrep\upm\node_modules\mysql2\lib\connection.js:117:31)    
    at Socket.emit (node:events:514:28)
    at TCP.<anonymous> (node:net:323:12)
Emitted 'error' event on Connection instance at:
    at Connection._notifyError (D:\Users\NUS\Desktop\PeerPrep\upm\node_modules\mysql2\lib\connection.js:252:12)
    at Socket.<anonymous> (D:\Users\NUS\Desktop\PeerPrep\upm\node_modules\mysql2\lib\connection.js:123:12)    
    at Socket.emit (node:events:514:28)
    at TCP.<anonymous> (node:net:323:12) {
  fatal: true,
  code: 'PROTOCOL_CONNECTION_LOST'
}

Node.js v18.17.1
ERROR: "start:server" exited with 1.
```

**Comment by lhy-hoyin** [comment]
This can be fixed by using the correct way to catch errors. Existing try-catch does not work.
See this [commit](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g32/commit/3412a4d0b5583c6ce689fa4086c7e9065b662416) of a fork.

Issue shall be closed when the fork is merged back here.
