### ISSUE TITLE
Backend port not closed properly when terminating process

### ISSUE THREAD

**Issue by lhy-hoyin** [CS3219-AY2324S1/ay2324s1-course-assessment-g32#32]
To duplicate:
1. `cd backend`
2. `npm run dev` and let it start
3. Close the window/prompt
4. Run `npm run dev` (or `npm start`) again
5. Get error
```
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3001
    at Server.setupListenHandle [as _listen2] (node:net:1751:16)
    at listenInCluster (node:net:1799:12)
    at Server.listen (node:net:1887:7)
    at Function.listen (...\backend\node_modules\express\lib\application.js:635:24)
    at Object.<anonymous> (...\backend\server.js:25:5)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)

```

**Comment by lhy-hoyin** [comment]
Possible useful read: https://github.com/remy/nodemon/issues/1109

**Comment by lhy-hoyin** [comment]
Issues seems to be related to the closing after using `npm run dev` (related to nodemon).

**Comment by lhy-hoyin** [comment]
Issue seems to be isolated to MINGW64 (terminal launched via SourceTree), which does not prompt for batch job termination upon `Ctrl + C`. 
Using other terminals (eg. Command Prompt) seems to resolve the issue.
